# reference: https://yeasy.gitbooks.io/docker_practice/
version: "2"
services:
  redis:
    image: redis:4.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  scrawler:
    container_name: scrawer
    image: node:10-slim
    depends_on:
      - redis
    volumes:
      - .:/scrawer
    working_dir: /scrawer
    entrypoint: /scrawer/entrypoint.sh
