# reference: https://yeasy.gitbooks.io/docker_practice/
version: "3"
services:
  redis:
    ports:
      - "6379:6379"
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: pp_redis
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
      - "/data/redis/:/redis/data"
    env_file: ./config/common.env
    command: 
      - /bin/sh
      - -c
      - |
        redis-server --requirepass $REDIS_PASS
    expose:
      - "6379"
  mongo:
    ports:
      - "27017:27017"
    restart: always
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    volumes:
      - "/data/mongo:/data/db"

  scrawler:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pp_scrawler
    env_file: ./config/common.env
    volumes:
      - "./logs/:/home/pptruser/project/logs"
      - "./download/:/home/pptruser/project/download"
    command: 

    ports:
      - "8888:8888"
    expose:
      - "8888"
    command:
      - /bin/sh
      - -c
      - |
        # node src/index.js -s zhihu
        pm2-runtime pm2.json
    # tty: true
    # stdin_open: true
    links:
      - redis
